# -*- coding: utf-8 -*-
"""Untitled28.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BW4Na_ktyd4LgxyBQDf3Vs4SQAQkwfp0
"""

import random

# گرفتن ورودی‌ها از کاربر
seed_input = input("کد قرعه‌کشی دلخواه (مثلاً lottery2025): ")
total_participants = int(input("تعداد کل شرکت‌کننده‌ها: "))
num_winners = int(input("تعداد برنده‌ها: "))

# تنظیم بذر (seed) برای تولید عدد تصادفی قابل تکرار
random.seed(seed_input)

# تولید لیست شرکت‌کننده‌ها (شماره‌ها از 1 تا n)
participants = list(range(1, total_participants + 1))

# انتخاب تصادفی برنده‌ها
winners = random.sample(participants, num_winners)

# نمایش نتایج
print("\n✅ برنده‌های قرعه‌کشی:")
for i, winner in enumerate(winners, start=1):
    print(f"{i}. شماره {winner}")

import numpy as np
import matplotlib.pyplot as plt

# تعریف x از -5 تا +5 با 500 نقطه
x = np.linspace(-5, 5, 500)

# تعریف اولیه‌ی y به صورت آرایه‌ای از صفرها
y = np.zeros_like(x)

# محاسبه y = x^3
y = x ** 3

# پر کردن فضای زیر نمودار با رنگ آبی و شفافیت 0.3
plt.fill_between(x, y, color='blue', alpha=0.3)

# رسم نمودار با خط‌چین
plt.plot(x, y, linestyle='--', color='green', label='y = x³')

# برچسب‌ها و نمایش
plt.title("y = x³")
plt.xlabel("x")
plt.ylabel("y")
plt.grid(True)
plt.legend()
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# تعریف x از -5 تا +5 با 500 نقطه
x = np.linspace(-5, 5, 500)

# محاسبه y = cos(0.5 * x)
y = np.cos(0.5 * x)

# پر کردن فضای زیر نمودار با رنگ آبی و شفافیت 0.3
plt.fill_between(x, y, color='blue', alpha=0.3)

# رسم نمودار با خط‌چین
plt.plot(x, y, linestyle='--', color='purple', label='y = cos(0.5x)')

# برچسب‌ها و نمایش
plt.title("y = cos(0.5x)")
plt.xlabel("x")
plt.ylabel("y")
plt.grid(True)
plt.legend()
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# تعریف x از -5 تا +5 با 500 نقطه
x = np.linspace(-5, 5, 500)

# محاسبه y = e^(-x^2)
y = np.exp(-x**2)

# پر کردن فضای زیر نمودار
plt.fill_between(x, y, color='blue', alpha=0.3)

# رسم تابع با خط‌چین
plt.plot(x, y, linestyle='--', color='red', label='y = e^(-x²)')

# تنظیمات نمودار
plt.title("y = e^(-x²)")
plt.xlabel("x")
plt.ylabel("y")
plt.grid(True)
plt.legend()
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# تعریف x از -5 تا +5 با 500 نقطه
x = np.linspace(-5, 5, 500)

# محاسبه y = e^(-x^2) * cos(0.5 * x)
y = np.exp(-x**2) * np.cos(0.5 * x)

# پر کردن فضای زیر نمودار
plt.fill_between(x, y, color='blue', alpha=0.3)

# رسم نمودار با خط‌چین
plt.plot(x, y, linestyle='--', color='darkorange', label='y = e^(-x²) * cos(0.5x)')

# تنظیمات نمودار
plt.title("y = e^(-x²) * cos(0.5x)")
plt.xlabel("x")
plt.ylabel("y")
plt.grid(True)
plt.legend()
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# تعریف x از -5 تا +5 با 500 نقطه
x = np.linspace(-5, 5, 500)

# تعریف توابع
y1 = np.exp(-x**2)
y2 = np.cos(0.5 * x)

# رسم تابع y1 با رنگ قرمز و پر کردن زیر آن با صورتی
plt.fill_between(x, y1, color='red', alpha=0.2, label='y = e^(-x²)')
plt.plot(x, y1, linestyle='--', color='red', label='y = e^(-x²)')

# رسم تابع y2 با رنگ آبی و پر کردن زیر آن با آبی روشن
plt.fill_between(x, y2, color='blue', alpha=0.2, label='y = cos(0.5x)')
plt.plot(x, y2, linestyle='--', color='blue', label='y = cos(0.5x)')

# تنظیمات نمودار
plt.title("y1 = np.exp(-x**2)--- y2 = np.cos(0.5 * x)")
plt.xlabel("x")
plt.ylabel("y")
plt.grid(True)
plt.legend()
plt.show()